version: "3"
services:
  database:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_DB=debugzilla
      - POSTGRES_USER=debugzilla_user
      - POSTGRES_PASSWORD=debugzilla_pass
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: